### ISSUE TITLE
use new travis file setup: add ons and other htings

### ISSUE THREAD

**Issue by sckott** [ropensci/lawn#46]
e.g,  for the v8 dep

```
addons:
  apt:
    packages:
      - libv8-dev
```
